type: chart
rootfs:
  - image: samsung_cnct/cluster-controller
    context: cluster-controller
    chart: cluster-controller
    value: images.repository
    dockerContext: .
configs:
  - chart: cluster-controller
    timeout: 600
    retries: 2
    release: cluster-controller
test:
  # TODO: add test for verify codegen
stage:  
prod: 
  doDeploy: none
