# Default values for cluster-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: samsung_cnct/cluster-controller:latest
  # TODO version this
  # tag: lastest
  pullPolicy: IfNotPresent

krakenClusterShortNames: kc

service:
  type: ClusterIP
  externalPort: 80
  internalPort: 80

resources: {}
  # requests:
  #   cpu: 10m
  #   memory: 32Mi