apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition

metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ template "name" . }}
    chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 }}
spec:
  group: {{ .Values.service.group }}
  version: {{ .Values.service.version }}
  scope: {{ .Values.service.scope }}
  names:
    plural: {{ .Values.service.names.plural }}
    singular: {{ .Values.service.names.singular }}
    kind: {{ .Values.service.names.kind }}
    shortnames:
      - {{ .Values.service.names.shortnames }}
  validation:
      openAPIV3Schema:
        properties:
          spec:
            required:
            - customerID
            - cloudProvider
            - provisioner
            - cluster
            properties:
              customerID:
                type: string
              cluster:
                type: object
                required:
                - clusterName
                - fabric
                - nodePools
                properties:
                  clusterName:
                    type: string
                  nodePools:
                    type: array
                    items:
                      type: object
                      required:
                      - name
                      - size
                      - machineType
                      - os
                      properties:
                        name:
                          type: string
                        size:
                          type: integer
                        publicIPs:
                          type: boolean
                        machineType:
                          type: string
                        os:
                          type: string
                  fabric:
                    type: object
                    required:
                    - name
                    properties:
                      name:
                        type: string
              cloudProvider:
                type: object
                required:
                - name
                properties:
                  name:
                    type: string
                  credentials:
                    type: object
              provisioner:
                type: object
                required:
                - name
                properties:
                  name:
                   type: string